# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37a585a12307cd829629a6315999c2eb48127cc36a36f451c142aa5142b4742e60986072acc4d02ceec95d3402d3ecc49b2dbb38ab0352bbd1775615962c1cb7

test:
  secret_key_base: a48e65e59a1c0359ae308f3694b11d4c47bbd94501f69f2036942e6a8319374bb017b996955fb993ec9f8afaae99a3b6d18c0931cc2d10d80238262f6b5a8f02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
